### ISSUE TITLE
Add architecture image to quickstart sample

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/azure-health-data-services-toolkit#104]
All azd public templates should have an architecture diagram. The azd product team asked that we add one. I suggest that we add two - one with APIM as the main template and one without.

We also should align the quickstart documentation to the azd samples.

Example here: https://github.com/Azure-Samples/todo-csharp-sql-swa-func

**Comment by evachen96** [comment]
Removed azd quickstart
