### ISSUE TITLE
IServiceCollection does not contain a definition for UseAuthenticator

### ISSUE THREAD

**Issue by dkirby-ms** [microsoft/azure-health-data-services-toolkit#109]
I am trying to follow the docs to setup the Quickstart project with VSCode. When I try to run the function app locally I am hit with this error. What am I doing wrong?

![image](https://github.com/microsoft/azure-health-data-services-toolkit/assets/32211549/b112333e-225f-48d2-8cd8-c2c2d2a4f858)

**Comment by dkirby-ms** [comment]
Any update? Is this toolkit still being maintained?

**Comment by evachen96** [comment]
Hi! The team is looking into this and we will get back when we have an update. Appreciate the patience.

**Comment by dkirby-ms** [comment]
@evachen96 sorry to keep bumping this but this is somewhat of a blocker for a customer scenario. Is there anyone I can work with directly on getting the toolkit functional in my environment?

**Comment by evachen96** [comment]
@dkirby-ms Sorry for the long wait, our SME is coming back from leave soon and we should be able to get working on a permanent fix, which I can let you know about when it gets deployed. In the meantime, one workaround that we've found is that if you re-run the quickstart (azd provision again) then it should work on the second try. Let me know if that works for you!

**Comment by mikaelweave** [comment]
@dkirby-ms - Thanks for your patience! We had a breaking change recently - you will need to make sure you have the most recent version of the `main` branch checked out on your system of this repository and deploy from this location.

We used to have a "ghost" repo for this Quickstart, but we had automation and scripts just to copy files from this repo to a new repo which just enabled the `azd init` command. 

The new workflow will be to just ensure this repository is cloned and up to date on your local system. Then run `azd up` from the `samples/Quickstart` folder to deploy the latest infra/code.

**Comment by dkirby-ms** [comment]
Thanks. I cloned a fresh copy of the repo, ran azd up and now I am hitting ServiceUnavailable from host runtime when trying to deploy the functions code.

![image](https://github.com/microsoft/azure-health-data-services-toolkit/assets/32211549/eabaa59a-6e34-4043-8526-aede89ef40f4)

**Comment by dkirby-ms** [comment]
I ran azd up again and the error didnt occur. I think I am good to go. Thanks for the help.

**Comment by mikaelweave** [comment]
Awesome @dkirby-ms! Thanks for responding. We were removing some code that conflicted with the Azure SDK. Thank you for your patience. 😄
