### ISSUE TITLE
Quickstart template repo no longer exists

### ISSUE THREAD

**Issue by pjirsa** [microsoft/azure-health-data-services-toolkit#110]
**Describe the bug**
When following the getting started section, running `azd init --template Azure-Samples/azure-health-data-services-toolkit-fhir-function-quickstart` fails because that repo no longer exists.

**To Reproduce**
see description

**Expected behavior**
azd init command should complete successfully and create my new local project.

**Actual behavior**
fails with:
```bash
ERROR: init from template repository: fetching template: failed to clone...
remote: Repository not found.
```

**Comment by evachen96** [comment]
Hi @pjirsa , we are in the middle of fixing up our quickstart template, I'll let you know when it's fixed and ready to go!

**Comment by pjirsa** [comment]
@evachen96 LMK how I can help!

**Comment by kyle-mwnz** [comment]
@evachen96  Is there any other option available to get started?

**Comment by evachen96** [comment]
@kyle-mwnz We are still working on getting the quickstart fixed, but one workaround that we've found is that if you re-run the quickstart (azd provision again) then it should work on the second try. @erikhoward  can help if you have more questions. I'll update when we have a permanent fix. Thanks for your patience!

**Comment by kyle-mwnz** [comment]
Running a subsequent `azd provision` removes the error returned from the CLI, but the resource still seems to be in an unusable state after running `azd deploy`. There are errors relating to the .net version when publishing - the readme and iac seems to target .net6, but there is a globals.json file targeting v7?

![image](https://github.com/microsoft/azure-health-data-services-toolkit/assets/83252538/ff6e74db-4546-4078-a61f-ffebbffb8b47)

I'll probably need to pause this and wait for a quickstart template to be available - I only have a couple of days to evaluate if this will work for use at a client

**Comment by evachen96** [comment]
@kyle-mwnz You should be able to modify the global .json file and change it to the .NET version that you're using, let me know if that works!

**Comment by kyle-mwnz** [comment]
As mentioned - I've tried many combinations of .NET versions, the Function app is still in the above error state

**Comment by evachen96** [comment]
@kyle-mwnz Apologies Thanks for your patience! We just merged a PR that should fix this, please make sure you have the most recent version of the main branch and deploy the quickstart with the new instructions: https://github.com/microsoft/azure-health-data-services-toolkit/tree/main/samples/Quickstart . Please let us know if you still run into issues!
