### ISSUE TITLE
Quickstart Sample Readme

### ISSUE THREAD

**Issue by w-matt-long** [microsoft/azure-health-data-services-toolkit#47]
Prereq section specifies "azd --version", which should be "azd version" 

Prerequisite check
In a terminal or command window, run dotnet --version to check that the .NET SDK is version 6.0 or later.
Run az --version and azd --version to check that you have the appropriate Azure command-line tools installed.

**Comment by mikaelweave** [comment]
Fixed in Quickstart repo
