### ISSUE TITLE
Quickstart Readme

### ISSUE THREAD

**Issue by w-matt-long** [microsoft/azure-health-data-services-toolkit#48]
In the Deploy Resources section of the Quickstart Readme, the line "Deploy the needed resources by running: azd provision" should be preceded by an line telling the user to run "az login"; otherwise if the user is not logged in then the "azd provision" command will fail.

Deploy Resources
Clone this repository and open a terminal or command window to this folder samples/Quickstart.
Deploy the needed resources by running: azd provision
This will take about 20 minutes to deploy the FHIR Service.
If you have run this sample in the past, using the same environment name and location will reuse your previous resources.

**Comment by mikaelweave** [comment]
This has been fixed with the new quickstart template!
