### ISSUE TITLE
RestBinding security token is always null

### ISSUE THREAD

**Issue by w-matt-long** [microsoft/azure-health-data-services-toolkit#53]
The RestBinding security token will always be null, i.e., lines 88-92.

The code should be more below such that the security token will be set if the IAuthenticator is not null.

string securityToken = null;
                if (authenticator != null)
                {
                    string userAssertion = authenticator.RequiresOnBehalfOf ? context.Request.Headers.Authorization.Parameter.TrimStart("Bearer ".ToCharArray()) : null;
                    securityToken = await authenticator.AcquireTokenForClientAsync(options.Value.ServerUrl, options.Value.Scopes, null, null, userAssertion);
                }

**Comment by evachen96** [comment]
This has been fixed
