### ISSUE TITLE
RestBinding to non-existing url should not return 500 but 404

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/azure-health-data-services-toolkit#54]
**Describe the bug**
When creating a custom operation for a single record (like Patient/<id>), the RestBinding will throw a 500 if a client requests a record that does not exist.

**To Reproduce**
1. Create a web or function pipeline with a binding that points to a FHIR server (+ an authenticator)
2. Send a request to the FHIR server through the pipeline for a record that doesn't exist (like `Patient/123`).

**Expected behavior**
There should at least be an option to not fail on HTTP status codes between 202 and 499 but to pass this through. Especially for 300-400. I don't think "`EnsureStatusSuccessful` in the RestBinding is correct

**Actual behavior**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/753437/186690536-a9e694a2-c350-431c-83df-c0fce2ce462d.png)

**Comment by w-matt-long** [comment]
Agree. Removing "EnsureStatusSuccessful" from RestBinding would simply return response what to do with the non-200 status code, which should be the behavior.

**Comment by vmsuthar56** [comment]
As Suggested we have removed the "EnsureStatusSuccessful." So if patient is not there it will return 404 or if patient is deleted then 410.

**Comment by mikaelweave** [comment]
@vmsuthar56 - is this live? 😄 If so can you close the issue?
