### ISSUE TITLE
Comment Error samples/FeatureSamples/ServiceBusChannel/Program.cs

### ISSUE THREAD

**Issue by w-matt-long** [microsoft/azure-health-data-services-toolkit#56]
An error/nit in the comment in samples/FeatureSamples/ServiceBusChannel/Program.cs
the first line of the comment is "Adds Service Busas", which should be "Add Service Bus"
the second line of the comment is "too large for Storage Bus.", which should "too large for the Service Bus SKU."

       // Adds Service Busas the first input channel. Azure Storage is a backing store for events that are
        // too large for Storage Bus.
        services.AddInputChannel<ServiceBusChannelOptions>(typeof(ServiceBusChannel), options =>
        {

**Comment by vmsuthar56** [comment]
Bug fix and merged to main
