### ISSUE TITLE
Expose Response Headers to Pipeline

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/azure-health-data-services-toolkit#78]
**Is your feature request related to a problem? Please describe.**
For using the Toolkit with Azure AD, we need the ability to modify the response headers. This is necessary for modifying the Azure AD flow and having clients redirect to the newly formed AAD URL with a Http redirect.

**Describe the solution you'd like**
It would be great if the OperationContext for the pipeline exposes a headers collection. This could be initialized as empty, binding could conditionally update this (by binding config), then output filters could modify the header collection.

**Describe alternatives you've considered**
Shim on top of the pipeline inside my program. Works but doesn't keep code segmented in the filter.

**Comment by w-matt-long** [comment]
Why not use the same pattern for response headers as request headers?

**Comment by mikaelweave** [comment]
@w-matt-long That's the plan 😄

**Comment by mikaelweave** [comment]
Completed
