### ISSUE TITLE
502 web server invalid response on attempt to create a new patient using the PatientPost Function

### ISSUE THREAD

**Issue by saikovvuri** [microsoft/azure-health-data-services-toolkit#96]
Deployed the quickstart sample as per the guide. However when trying to create a new patient using the patient.json file content under the tests folder , getting the below error

![image](https://user-images.githubusercontent.com/7659507/211472673-f12e9fbb-0e97-49e9-9e52-062bd4d72ea2.png)

**Comment by evachen96** [comment]
This should be fixed with the last PR, thanks!
